project_id = "vedgkzikqccykuozkmxl"

[functions.calculate-daily-charges]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.auto-clockout-handler]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = true
